### ISSUE TITLE
antsRegistration core usage

### ISSUE THREAD

**Issue by edeguzman** [functional-neuroimaging/rsfMRI-preprocessing#4]
It seems that the default mode of antsRegistration is to use all cores available, which is inconvenient if more than 1 person is trying to work on the same workstation (and we want to tightly control the number of cores each person uses). It looks like "ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS" can be specified in order to set the number of threads. Is it possible to add setting of this variable to the registration script so we can control the max number of threads? @marcopagani-brainconnectivity, can we look into this?

**Comment by marcopagani-brainconnectivity** [comment]
Yes, that is the way to go when multiple users share the same workstation or server

From: Elizabeth de Guzman ***@***.***>
Sent: Thursday, August 11, 2022 6:01 AM
To: functional-neuroimaging/rsfMRI-preprocessing ***@***.***>
Cc: Marco Pagani ***@***.***>; Mention ***@***.***>
Subject: [functional-neuroimaging/rsfMRI-preprocessing] antsRegistration core usage (Issue #4)


It seems that the default mode of antsRegistration is to use all cores available, which is inconvenient if more than 1 person is trying to work on the same workstation (and we want to tightly control the number of cores each person uses). It looks like "ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS" can be specified in order to set the number of threads. Is it possible to add setting of this variable to the registration script so we can control the max number of threads? @marcopagani-brainconnectivity<https://es.sonicurlprotection-fra.com/click?PV=2&MSGID=202208111001300209036&URLID=3&ESV=10.0.16.7295&IV=301BA40F54EB28DF724BCDC0FFE301A9&TT=1660212091735&ESN=mYypPXqPxzyeBC%2FNydmMlkEaNIbKatp1M0lXQdYC2W8%3D&KV=1536961729280&B64_ENCODED_URL=aHR0cHM6Ly9naXRodWIuY29tL21hcmNvcGFnYW5pLWJyYWluY29ubmVjdGl2aXR5&HK=ABE83B49C4BCBB47A35E3711A07E4220914F53AF6BE167449F05F76212B4618F>, can we look into this?

**Comment by edeguzman** [comment]
Great. Are you going to implement this, @marcopagani-brainconnectivity? Let me know if you need help testing.

**Comment by silvia-gini** [comment]
Hi, we found this discussion helpful to solve the issue: https://sourceforge.net/p/advants/discussion/840260/thread/05a5a703/ . Adding at the top of the script outside the function allows you to set the number of threads called by antsRegistration:

export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=2
